services:
  macos:
    image: dockurr/macos
    container_name: macos-15
    environment:
      VERSION: "15"
      DISK_SIZE: "256G"
      RAM_SIZE: "16G"
      CPU_CORES: "6"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    restart: unless-stopped
    stop_grace_period: 2m